
INSERT INTO products (
  id,
  sku,
  name,
  subtitle,
  category,
  sub_category,
  gender,
  price,
  original_price,
  discount_percent,
  is_new,
  is_sale,
  in_stock,
  stock_count,
  image,
  description,
  care_instructions,
  sizes,
  colors
)
VALUES (
  'kimia-silk-dress',
  'KMY-BLK-01',
  'پیراهن ابریشمی مدل کیمیا',
  'زنانه - ابریشم خالص با برش هندسی',
  'women',
  'dress',
  'women',
  12500000,
  12500000,
  0,
  1,
  0,
  1,
  18,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuBEzADUZc4DsnjQhmVa8YUFniqeMTuVMkguHuJ-KeQSVUGsEbaFj64SVpdji7rRbxo_e_pI8KDBh8do2AyMaHpVU6GQ205Uvvthbo_-3gmzh8F8u9EKmsETIufHMJ5Qp_jQd6WfxrPJ5mtUXApUo-yW_o4quB4ozP_BTQ3CdkfElL_2Q6FL2BEYf9HVQwTjdMryIrEVAOipNP1qI_SWa0BtF9GrOoEguCBsCbwr-zPvJeVskId_abdl',
  'این پیراهن ابریشمی با الهام از خطوط هندسی معماری ایرانی و مینیمالیسم معاصر طراحی شده است. استفاده از پارچه صد در صد ابریشم طبیعی توت، حس سبکی و لطافت بی‌نظیری به ارمغان می‌آورد. برشی آزاد و مینیمال برای استایلی مجلل در رویدادهای خاص.',
  'تنها خشکشویی شود. از اتوکشی با حرارت بالا خودداری کنید. در جای خشک و دور از نور مستقیم نگهداری شود.',
  '["۳۶","۳۸","۴۰","۴۲"]',
  '[{"name":"مشکی نیمه‌شب","hex":"#000000","bgClass":"bg-black"},{"name":"عاجی","hex":"#fffff0","bgClass":"bg-[#fffff0]"},{"name":"سبز زمردی","hex":"#046307","bgClass":"bg-[#046307]"}]'
);


INSERT INTO products (
  id,
  sku,
  name,
  subtitle,
  category,
  sub_category,
  gender,
  price,
  original_price,
  discount_percent,
  is_new,
  is_sale,
  in_stock,
  stock_count,
  image,
  description,
  care_instructions,
  sizes,
  colors
)
VALUES (
  'lotus-silk-blouse',
  'LTS-SLK-02',
  'شومیز ابریشم لوتوس',
  'زنانه - ابریشم خالص، کرم و زغالی',
  'women',
  'blouse',
  'women',
  4800000,
  6000000,
  20,
  0,
  1,
  1,
  12,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuB_aBlhiN5s97uzx8zJMsZUo-HanC8HTrtdmrQ1jxNzreufRptnDoDIvoWG1B-nGWhiIYSy6LvVrFKrlaAK2Ur0m0L0q7fGvzn-ZfxG2n0QqUosZ-kDh1MyyqgezTtWaEWmdL1jB8GAshEeMqoj7OoXpBMwM6lb-Wha-Pu7ikK5Gi8muVjRyo66u8eoujawoV-ecRK-EMJikwS3p36jAS8Wff_xan-Hp-9F75ohDCZmhMU5vqgFIX5B',
  'شومیز لوتوس با برش یقه گرد خاص و آستین‌های افتاده، تلفیقی از متانت و مدرنیته را در کنار درخشش مات ابریشم زغالی به نمایش می‌گذارد.',
  'شستشوی دستی با آب سرد و مایع مخصوص ابریشم. اتوکشی پشت پارچه با درجه ملایم.',
  '["S","M","L"]',
  '[{"name":"زغالی متالیک","hex":"#2b2b2b","bgClass":"bg-[#2b2b2b]"},{"name":"کرم شیری","hex":"#f5f0e6","bgClass":"bg-[#f5f0e6]"}]'
);


INSERT INTO products (
  id,
  sku,
  name,
  subtitle,
  category,
  sub_category,
  gender,
  price,
  original_price,
  discount_percent,
  is_new,
  is_sale,
  in_stock,
  stock_count,
  image,
  description,
  care_instructions,
  sizes,
  colors
)
VALUES (
  'classic-linen-trousers',
  'TR-LIN-03',
  'شلوار کتان کلاسیک',
  'طراحی یونیسکس - کتان اعلا',
  'men',
  'pants',
  'men',
  3150000,
  4500000,
  30,
  0,
  1,
  1,
  25,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuDwCiMEiHXtdA2ZPL774mMJVX8Xxqp_HYAIh8eP9anFiTpkpqrRZjuZj8zI6vgqaGkGguh1o7kLWB-vlo5sUY-VMzov8RurXzmzJybgZyl-xlpgJSziZL9ewlHnXtwTIOGCwRbcG9kf08RssiTn8UBMBpNjuyj8jpIuVeEiva_qpyk-Y1dgjY3d98A54HlHE2YPGhOSvZEcuI6dENJVHxWja9uoDrbrfVv3QX0I63hEYewB3o1N8lHd',
  'شلوار راسته کتان با خط اتوی برجسته و دمپای دوبل. طراحی شده با الهام از شلوارهای کلاسیک ایتالیایی و پارچه طبیعی تنفس‌پذیر.',
  'شستشو با ماشین در دمای ۳۰ درجه. اتوکشی در حالت نمدار.',
  '["S","M","L","XL","XXL"]',
  '[{"name":"کرم خاکی","hex":"#e5e2dd","bgClass":"bg-[#e5e2dd]"},{"name":"سرمه‌ای تیره","hex":"#1c2e4a","bgClass":"bg-[#1c2e4a]"},{"name":"مشکی","hex":"#000000","bgClass":"bg-black"}]'
);


INSERT INTO products (
  id,
  sku,
  name,
  subtitle,
  category,
  sub_category,
  gender,
  price,
  original_price,
  discount_percent,
  is_new,
  is_sale,
  in_stock,
  stock_count,
  image,
  description,
  care_instructions,
  sizes,
  colors
)
VALUES (
  'cashmere-pattern-scarf',
  'SCF-CSH-04',
  'شال کشمیر طرح‌دار',
  'اکسسوری - الیاف کشمیر با نقوش سنتی',
  'accessories',
  'scarf',
  'women',
  2975000,
  3500000,
  15,
  0,
  1,
  1,
  14,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuBx-zq6RgBLqezyQd_WS97l9t9EvrNphGrgK7hriSL7RVyUMwD4CtxMwIcITZOlWGf8ECfHisUyuiaRNG3xJkS_5XK8A3Ho5Qmr6d-8s3gZgvRPp-26ElMZ-Fkob9nN6NgRv1xg1k8inQjC9vbdKQShBsu5fqOgG-YDjObjcmIRDu17RRH6kLpD5KUJnrCmlCinC-wH2e7h-Qnb6SpBPXHfZSN2frhF9-aP8mhqr09t9iANte8HJWsY',
  'بافته شده از لطیف‌ترین کشمیر کوهستانی با ترنج و بته‌جقه‌های محو شاه‌عباسی، گرمابخش و وقارآفرین.',
  'خشکشویی اختصاصی کشمیر یا شستشوی ملایم با شامپو بچه در آب ولرم.',
  '["تک سایز (۲۰۰×۷۰)"]',
  '[{"name":"سرمه‌ای و بژ","hex":"#1a2c42","bgClass":"bg-[#1a2c42]"}]'
);


INSERT INTO products (
  id,
  sku,
  name,
  subtitle,
  category,
  sub_category,
  gender,
  price,
  original_price,
  discount_percent,
  is_new,
  is_sale,
  in_stock,
  stock_count,
  image,
  description,
  care_instructions,
  sizes,
  colors
)
VALUES (
  'yalda-wool-coat',
  'COT-WLD-05',
  'پالتو پشمی یلدا',
  'زنانه - دوخت دستی و پشم اعلا',
  'women',
  'coat',
  'women',
  12500000,
  12500000,
  0,
  1,
  0,
  1,
  8,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuAqnqzVlw7oFtMSE1DeLoywdw8f8DcjqgZYyHlqhJiTiTYW0NbRXXXVLtoew5dW-YYbo0mKyAe0osRLivNpNMdyq1CtP3Nv0jTrwuvMzre3_m77aVGmIX0jBYZMUFgfyP4oJ3I1Af8LGFd8jobzR7c9S5sKtizJcgUrxRRlZPxIqHtxiG1VnRTovXzFFzigHhEke9dnWEOHQz3YMJWWzBNju_swpulAoAySCUYGdDiIRVpo9BCbrIXT',
  'پالتوی اوورسایز با یقه ایستاده ظریف و مغزی‌دوزی‌های دست‌ساز سنتی در سرآستین‌ها. گرمای پشم طبیعی همراه با وقار اصیل ایرانی.',
  'خشکشویی حرفه‌ای.',
  '["۳۸","۴۰","۴۲"]',
  '[{"name":"زغالی گرافیتی","hex":"#383b3d","bgClass":"bg-[#383b3d]"}]'
);


INSERT INTO products (
  id,
  sku,
  name,
  subtitle,
  category,
  sub_category,
  gender,
  price,
  original_price,
  discount_percent,
  is_new,
  is_sale,
  in_stock,
  stock_count,
  image,
  description,
  care_instructions,
  sizes,
  colors
)
VALUES (
  'aria-blazer-jacket',
  'JKT-ARA-06',
  'کت بلیزر آریا',
  'مردانه - کتان اعلا و برش اسلیم فیت',
  'men',
  'blazer',
  'men',
  9800000,
  9800000,
  0,
  1,
  0,
  1,
  15,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuBrWaQHneJA_N2PuyFBQ4DJUys5-NunaYwnFaqcPIiHGvFfa4YY27czzuyJ3rP-ciZXgwHScTKuL_3c7mNuybS70Uc4G7NDQIYfhYENXuxl8o45w0zjJK6Xzmv9QkjcqtQXU4FkV-IjowkmEIGco413f2IC0ifrVEOFXto-_C1VKgspxsFjw2DNaeAewf0imVymJAETK9AV0rV62Ycs8hJ1CCGYXtaqE8pm7vk51xFg7jByBwkZOd13',
  'کت تک دکمه تک‌چاک با سرشانه‌های طبیعی و آستر ساتن ابریشمی، مناسب مراسم‌های تشریفاتی و محیط‌های حرفه‌ای.',
  'خشکشویی با بخار ملایم.',
  '["48","50","52","54"]',
  '[{"name":"مشکی مات","hex":"#111111","bgClass":"bg-[#111111]"},{"name":"سرمه‌ای درباری","hex":"#152238","bgClass":"bg-[#152238]"}]'
);


INSERT INTO products (
  id,
  sku,
  name,
  subtitle,
  category,
  sub_category,
  gender,
  price,
  original_price,
  discount_percent,
  is_new,
  is_sale,
  in_stock,
  stock_count,
  image,
  description,
  care_instructions,
  sizes,
  colors
)
VALUES (
  'kashan-silk-scarf',
  'SCF-KSH-07',
  'شال ابریشم کاشان',
  'زنانه - ابریشم خالص با حاشیه طلایی',
  'accessories',
  'scarf',
  'women',
  3200000,
  3200000,
  0,
  1,
  0,
  1,
  30,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuCuujt880UInIsK8m7S2kWD32rSzPLsDKBj4RL4E9Gjb3fmCDiWxvES4mX4SExkH-IimyavfYuX_GbQQ6x8_mglYPfAV4Wh7uZ63yYSWbdIAIldEoDghXgheGZ9CsKkcmKD2h9Gz7wV1-RRIrgA3aj1Oz8pjzU9k6BxsVqNsT1M5MOnKwp2e7J83hFh-T1fyL1eMxE8NGfC85pD27i0a_WEjY2q1rq-s-znvimhOETJTumO8NTfpQ4D',
  'بافت سنتی با ابریشم مرغوب کاشان و چاپ دستی باتیک، تلفیقی چشم‌نواز از رنگ‌های کویری و آبگینه‌ای.',
  'شستشوی خشک یا با آب سرد.',
  '["تک سایز (۱۹۰×۷۰)"]',
  '[{"name":"سرمه‌ای نیلی","hex":"#1c2e4a","bgClass":"bg-[#1c2e4a]"},{"name":"خاکی هلویی","hex":"#d8a892","bgClass":"bg-[#d8a892]"}]'
);


INSERT INTO products (
  id,
  sku,
  name,
  subtitle,
  category,
  sub_category,
  gender,
  price,
  original_price,
  discount_percent,
  is_new,
  is_sale,
  in_stock,
  stock_count,
  image,
  description,
  care_instructions,
  sizes,
  colors
)
VALUES (
  'oxford-leather-shoes',
  'SH-OXF-08',
  'کفش چرم آکسفورد',
  'مردانه - چرم طبیعی دست‌دوز تبریز',
  'men',
  'shoes',
  'men',
  7500000,
  7500000,
  0,
  1,
  0,
  1,
  10,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuDwcIGmEkJfKXwKMcqXS43Frgl5LBdZ96gc6avkOvUd815_ft1UfuqbjSycx1GnHMg3dlyqassqR8FB7zYU1eiYzogKUJgEKXjbkvVWmuvaJrf2TJkCSAUJUDn5_rJXAaReKTuCTC6IRYPzouWuo78GrduDRk0fSZRsBzongVgS7BkTWXu99HGZyQrkZ4iaTgyTwUJRoOrmWUjzPD_ce7jWzmBHcAamEoWW1XtXKFrdRgMKO7suFG7f',
  'چرم صد در صد گاوی اعلای دباغی گیاهی تبریز با زیره چرم طبیعی و پاشنه لاستیکی ضدلغزش.',
  'واکس مخصوص موم زنبور عسل و استفاده از قالب چوبی کفش.',
  '["40","41","42","43","44","45"]',
  '[{"name":"مشکی براق","hex":"#000000","bgClass":"bg-black"},{"name":"قهوه‌ای تیره","hex":"#4a3525","bgClass":"bg-[#4a3525]"}]'
);


INSERT INTO products (
  id,
  sku,
  name,
  subtitle,
  category,
  sub_category,
  gender,
  price,
  original_price,
  discount_percent,
  is_new,
  is_sale,
  in_stock,
  stock_count,
  image,
  description,
  care_instructions,
  sizes,
  colors
)
VALUES (
  'tabriz-leather-bag',
  'BAG-TBZ-09',
  'کیف چرم تبریز',
  'زنانه - چرم ساختاریافته مینیمال',
  'accessories',
  'bag',
  'women',
  4800000,
  4800000,
  0,
  0,
  0,
  1,
  6,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuCYPSBzemx1-M5DoVsiLRc8ieJndcU1TqlT5fOkSY2qXwbYb-fzi7ngfb8xN0mu_RZZGzRAvvZG7EVWDgDfWyE68g0sY3lKYFXs25IkmCyHcfdiqCyiqpMrhvTLXUw8E5E1R-d-tMXHTFPAPLbBXLGMLv7V0zuL7gtRudGy56WbKxkvkTFXQtmYYHIla_mcEuvENx86NqBQpS7Fv6pVw_X1StFbJfVNB-AgIejJPDqroE5BJkPs-Y-M',
  'فرم هندسی قاطع با یراق‌آلات برنجی مات ضد زنگ و بند دوشی قابل تنظیم.',
  'تمیز کردن با پارچه میکروفیبر نرم و لوسیون مخصوص چرم طبیعی.',
  '["استاندارد (۲۸×۲۰×۱۰)"]',
  '[{"name":"زغالی گرافیتی","hex":"#222222","bgClass":"bg-[#222222]"}]'
);


INSERT INTO products (
  id,
  sku,
  name,
  subtitle,
  category,
  sub_category,
  gender,
  price,
  original_price,
  discount_percent,
  is_new,
  is_sale,
  in_stock,
  stock_count,
  image,
  description,
  care_instructions,
  sizes,
  colors
)
VALUES (
  'mina-gold-bracelet',
  'JW-MNA-10',
  'دستبند طلا طرح مینا',
  'جواهرات - دست‌ساز با حکاکی خط نستعلیق',
  'accessories',
  'jewelry',
  'women',
  18500000,
  18500000,
  0,
  0,
  0,
  1,
  4,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuBb15wJ2YOnMRlC1jNxF9IQjWPsPB9KKx1AVm5K_I6405iEEe1Whn7BUySWE8iN_k7NhiHRFMbhtuoT1lXiyB6soXGHJwFvm-JMZcohjADznh1whCXZ_rzlBE91Jgc5ZfyaSXcO6GRLhrrldgriDgj0XWjLNx0pmmaxNEQZ4fNn61GsDdtPf-HZB4tCGjZIutzJW7xAyGYCQeC8vMtTlWI3365izjWPZQ1iYpXZjOD67iFS_ZYdNUSS',
  'دستبند النگویی باز با بیت زیبای ''عشق و هنر'' حکاکی شده با دست توسط استادکاران قلم‌زنی اصفهان.',
  'جلوگیری از برخورد با مواد شوینده، عطر و اسپری.',
  '["تک سایز با قابلیت تنظیم"]',
  '[{"name":"طلای ۱۸ عیار مات","hex":"#d4af37","bgClass":"bg-[#d4af37]"}]'
);


INSERT INTO products (
  id,
  sku,
  name,
  subtitle,
  category,
  sub_category,
  gender,
  price,
  original_price,
  discount_percent,
  is_new,
  is_sale,
  in_stock,
  stock_count,
  image,
  description,
  care_instructions,
  sizes,
  colors
)
VALUES (
  'artemis-structural-manteau',
  'MAN-ART-11',
  'مانتو ساختاری آرتمیس',
  'زنانه - طراحی مینیمال، مشکی زغالی',
  'women',
  'manteau',
  'women',
  4500000,
  4500000,
  0,
  1,
  0,
  1,
  16,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuBiqyAry9F5Y7DG473ynslau61ilLqgkYIPFUo1RiOHtcJ15opM9knBPHITHAvFcLX5YpeTfLklrkB-HPg7srl0QdilW7dDxHk8e7uHXytPbK6TiVMZBIkK9Y9gGHH26BjJnm7SMXtjZpJAcaU0ZCodL9p1SRrn1cG8lWs2T_DInuatAu6QElV6BBilo-71TvOVNdbzmPcuAvD7rzx3nPIv3bcwUqRdhO43oq5x7JjAdg13i76DiVUM',
  'مانتو با ساختار ژئومتریک و آستین‌های فرم‌دار، دوخته شده از کرپ ابریشم درجه یک، بدون چروک‌پذیری.',
  'خشکشویی یا شستشوی ملایم.',
  '["S","M","L"]',
  '[{"name":"مشکی زغالی","hex":"#1f1f1f","bgClass":"bg-[#1f1f1f]"}]'
);


INSERT INTO products (
  id,
  sku,
  name,
  subtitle,
  category,
  sub_category,
  gender,
  price,
  original_price,
  discount_percent,
  is_new,
  is_sale,
  in_stock,
  stock_count,
  image,
  description,
  care_instructions,
  sizes,
  colors
)
VALUES (
  'parmida-wide-pants',
  'TR-PRM-12',
  'شلوار واید پارمیدا',
  'زنانه - دوخت سفارشی، خاکی',
  'women',
  'pants',
  'women',
  3200000,
  3200000,
  0,
  0,
  0,
  1,
  19,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuCs4Zsg7slhju6qUMLwX7HSQdPIwgBUIa_bU7KwS7fW25WtccmBl0wsFtG3GdOQa9mugBQXcJbIQ3e31zw3TBx_oPw3uZ5wz4LTt6UP6-CxxAJh2OXGIb_f1hkuMM28o-72vPeuLe1cPawprf-xEfB0LtTdSRkKLn6HLn1Zlj06BclmRxecpc8GjuB-XAGgCO9xUVKefZAukvNG-zUTzpbdQ5aUfPie2I8sdU_fYOrV7jnqQ-7YGzrD',
  'شلوار واید لگ با فاق بلند و پل کمربند ظریف، کشیدگی اندام و راحتی فوق‌العاده در طول روز.',
  'شستشو با ماشین در آب ولرم.',
  '["۳۶","۳۸","۴۰"]',
  '[{"name":"خاکی زیتونی","hex":"#9f9988","bgClass":"bg-[#9f9988]"},{"name":"مشکی","hex":"#000000","bgClass":"bg-black"}]'
);


INSERT INTO products (
  id,
  sku,
  name,
  subtitle,
  category,
  sub_category,
  gender,
  price,
  original_price,
  discount_percent,
  is_new,
  is_sale,
  in_stock,
  stock_count,
  image,
  description,
  care_instructions,
  sizes,
  colors
)
VALUES (
  'diplomat-wool-blazer',
  'JKT-DPL-13',
  'کت پشمی دیپلمات',
  'مردانه - پارچه راه‌راه پشمی با دوخت ایتالیایی',
  'men',
  'blazer',
  'men',
  14500000,
  14500000,
  0,
  0,
  0,
  1,
  7,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuD-pDkqb3WHgTsjCa01GILlV09U6zyuNJg7iMB30Ly1W4gUkS8CrxSqTeD-nDgFnzEyOj2p7bnE0ZZPh9OPPjn0iKuu82vhlvzgpBmXleFkAz0I4Bkqy4GV7-0z58rR9OTWCLZVk0cep7bKceShz6HfkLC4bOX0K8LjhPkL_aipiIoTT7WBZz57mdBF2Rq1cQPFQD-3_UsRbH6-N0QhKvSZoTD_FPsfqnFKUGCK2xjtZ15inn8HuAFO',
  'پارچه پشمی سوپر ۱۲۰ با خطوط دیپلمات نامحسوس، خوش‌دوخت و مقاوم در برابر چروک.',
  'خشکشویی تخصصی.',
  '["48","50","52","54"]',
  '[{"name":"خاکستری زغالی راه‌راه","hex":"#444444","bgClass":"bg-[#444444]"}]'
);


INSERT INTO products (
  id,
  sku,
  name,
  subtitle,
  category,
  sub_category,
  gender,
  price,
  original_price,
  discount_percent,
  is_new,
  is_sale,
  in_stock,
  stock_count,
  image,
  description,
  care_instructions,
  sizes,
  colors
)
VALUES (
  'oxford-cotton-shirt',
  'SHR-OXF-14',
  'پیراهن پنبه‌ای آکسفورد',
  'مردانه - پنبه خالص مصری، سفید کریستالی',
  'men',
  'shirt',
  'men',
  3200000,
  3200000,
  0,
  0,
  0,
  1,
  35,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuBhY8fd0YLJrqW_AA4TmPgpBzqEIPdQ85-73DO2QzjbTAVFehr6DAINuvLSZyCN4BNuOk0zxCRN6GIJ507SSXJSrDGKT9w9dHeuI0QCzJcQ65NSbXMvaaYSiAHISW77tU64_esbFXcCu7CWY0jfJ9z0_WajS-DJwzu-4r9B29KV50BZdHICaHeb9t6zJ7lKnTgpU7JxpJguG-B6cZT-tfqhdKgC_u4QE9MtaumrJuvarGCS3pKIetKy',
  'پیراهن کلاسیک با بافت آکسفورد متراکم، دکمه‌های صدف طبیعی و ایستایی بی‌نظیر یقه.',
  'شستشو با دمای ۴۰ درجه و اتوکشی بخار.',
  '["S","M","L","XL","XXL"]',
  '[{"name":"سفید خالص","hex":"#ffffff","bgClass":"bg-white"},{"name":"آبی آسمانی","hex":"#cce0ff","bgClass":"bg-[#cce0ff]"}]'
);


INSERT INTO products (
  id,
  sku,
  name,
  subtitle,
  category,
  sub_category,
  gender,
  price,
  original_price,
  discount_percent,
  is_new,
  is_sale,
  in_stock,
  stock_count,
  image,
  description,
  care_instructions,
  sizes,
  colors
)
VALUES (
  'navy-sport-blazer',
  'JKT-NVY-15',
  'کت تک اسپرت سرمه‌ای',
  'مردانه - کتان کش با آستر نیمه',
  'men',
  'blazer',
  'men',
  12000000,
  12000000,
  0,
  0,
  0,
  1,
  11,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuAU2QA4MiSgScwwOMDPPicNfLUNPWM5SA-3qj7ArucveOOoap1gJI5h4He4TWt3SMUI5ICDJYvLUFq-6YBS54BEJYq7Le0X-kgl6wyL4d_wMtaZDl8SHhdJoKHfvveF91noxNCqk5R2wFUGS0eqE4FBhzC13g_xQ4tuBP7pyUDD1zTseEM8YPIUVJNW-hDS9fsOXUeD6aN4VdsBG9l3rcCC16mEY6bxQ4zch1Q7tSGGZHa8xrE4FLi2',
  'کت تک همه‌کاره مناسب استایل کژوال با شلوار کتان یا استایل رسمی با شلوار پارچه‌ای.',
  'خشکشویی.',
  '["48","50","52","54"]',
  '[{"name":"سرمه‌ای سیر","hex":"#111f36","bgClass":"bg-[#111f36]"}]'
);


INSERT INTO products (
  id,
  sku,
  name,
  subtitle,
  category,
  sub_category,
  gender,
  price,
  original_price,
  discount_percent,
  is_new,
  is_sale,
  in_stock,
  stock_count,
  image,
  description,
  care_instructions,
  sizes,
  colors
)
VALUES (
  'white-structured-blazer',
  'JKT-WHT-16',
  'کت ساختاریافته سفید',
  'زنانه - کرپ سنگین با خطوط معماری',
  'women',
  'blazer',
  'women',
  8900000,
  8900000,
  0,
  1,
  0,
  1,
  9,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuDA0KTXIoEPseEAGMIlmDiAJxZjWw3Fx1jfzVHQkqKZLCb6MNPHLOCnZ7DPmdiVkqxGdeN2RUtv49YmuzMFCLKnLs-_H4DXdInfqSgGRy6Y6sQ7ainTVKaYp_a5F4YQDxthkMxvb_l1dHSiHHmsTMOahCyuMQ7-Zl1t3awmlB8CxgpXGZRVXhQyeo0QKvrb_LzNoz7EQ5pMXbP03qJRpkdMsskeWd1hiOf1qtuf-8VTZPsr7pf1CIc9',
  'کت خوش‌برش با لبه‌های دالبردار محو و برش کمر اسلیم، چشم‌نواز و شیک.',
  'خشکشویی تخصصی.',
  '["۳۶","۳۸","۴۰"]',
  '[{"name":"سفید استخوانی","hex":"#faf8f5","bgClass":"bg-[#faf8f5]"}]'
);


INSERT INTO products (
  id,
  sku,
  name,
  subtitle,
  category,
  sub_category,
  gender,
  price,
  original_price,
  discount_percent,
  is_new,
  is_sale,
  in_stock,
  stock_count,
  image,
  description,
  care_instructions,
  sizes,
  colors
)
VALUES (
  'long-beige-wool-coat',
  'COT-BGE-17',
  'پالتو پشمی بلند',
  'زنانه - فوتر کوبیده اعلا، شتری و کرم',
  'women',
  'coat',
  'women',
  18000000,
  18000000,
  0,
  0,
  0,
  1,
  5,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuCSKDNVWDWYdWg2it2Z6XXpgFcPbO9_VJbBSWoaQ3iA7ag0Alv1bmPIUAyByHgLf7DdUXL5J2rkIL2wCYWawJZVe2oGreFJ_gN2lAoxnHlNEkXI2X9VQHu-qDXe0G2E_mLRNhzMcJmMWs-buAYGhtSMSJVo9RTdLz4JGRvHo2mhfrLd5asMdiJuiSA7NvGsCB17L7W393U0fPARwI58Vjg9hiCK6vSL4ZU6E8a3rfGjhRyPbcu9WiR-',
  'پالتوی کلوش ماکسی با کمربند چرمی و یقه آرشال پهن، گرما و ابهتی بی‌بدیل.',
  'خشکشویی.',
  '["۳۸","۴۰","۴۲"]',
  '[{"name":"بژ شتری","hex":"#c3a887","bgClass":"bg-[#c3a887]"}]'
);


INSERT INTO products (
  id,
  sku,
  name,
  subtitle,
  category,
  sub_category,
  gender,
  price,
  original_price,
  discount_percent,
  is_new,
  is_sale,
  in_stock,
  stock_count,
  image,
  description,
  care_instructions,
  sizes,
  colors
)
VALUES (
  'burgundy-minimal-leather-bag',
  'BAG-BRG-18',
  'کیف چرم مینیمال',
  'زنانه - چرم طبیعی زرشکی عتیق',
  'accessories',
  'bag',
  'women',
  6500000,
  6500000,
  0,
  0,
  0,
  1,
  7,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuBrnDLpcfyzyhJTeqgzENp7c8KtdP0-c7KYlYlEWAN71c0eXTQuBwxV6ESgiwAsAWFPkwcBd23uLiBeF_xjDXPPKzHvfWle_TIQq4XtUdwMlNUiPfbWYuLEDplTzoLE-XD7lWRJFNjl1PijvDSNqCkWV_TPfQ_-IDmihAAvATES1zAcdL-Jt7cQgLPyax3r1HA4QO-RIY33ambkaf1oZZyJ2goHit6xwJU5NpOHQ54aZCq_yk39MM1M',
  'کیف دستی دسته کوتاه با قفل فلزی آبکاری طلا و دوخت ریز دستی هنرمندان چرم تبریز.',
  'محافظت از تماس با الکل و مواد شیمیایی.',
  '["استاندارد"]',
  '[{"name":"زرشکی عمیق","hex":"#5a1827","bgClass":"bg-[#5a1827]"}]'
);
